"""add payouts and disputes

Revision ID: 292e32a39912
Revises: 5615e97c0ea9
Create Date: 2026-09-23 15:00:43.417265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '292e32a39912'
down_revision: Union[str, Sequence[str], None] = '5615e97c0ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ledgeraccount ADD VALUE IF NOT EXISTS 'PAYOUT'")
    op.execute("ALTER TYPE milestonestatus ADD VALUE IF NOT EXISTS 'DISPUTED'")
    op.execute("ALTER TYPE milestonestatus ADD VALUE IF NOT EXISTS 'RESOLVED'")
    op.execute("ALTER TYPE contractstatus ADD VALUE IF NOT EXISTS 'DISPUTED'")

    # ... everything autogenerate wrote (create_table calls etc.) stays below, unchanged
    op.create_table('disputes',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('opened_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='disputestatus'), nullable=False),
    sa.Column('resolution_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_contract_id'), 'disputes', ['contract_id'], unique=False)
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_milestone_id'), 'disputes', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_disputes_opened_by'), 'disputes', ['opened_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_opened_by'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_milestone_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_contract_id'), table_name='disputes')
    op.drop_table('disputes')
    op.execute("DROP TYPE IF EXISTS payoutstatus")
    op.execute("DROP TYPE IF EXISTS disputestatus")
    # Postgres can't remove values from an enum once added, so PAYOUT stays on
    # ledgeraccount, and DISPUTED/RESOLVED stay on milestonestatus/contractstatus
    # even after a downgrade. That's expected, not a bug.
    # ### end Alembic commands ###
