"""create payment_transactions and processed_events tables

Revision ID: 713e2dc98738
Revises: 5615e97c0ea9
Create Date: 2026-09-24 00:23:21.083677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '713e2dc98738'
down_revision: Union[str, Sequence[str], None] = '5615e97c0ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
