"""create ledger_entries and idempotency_keys tables

Revision ID: c5636476777d
Revises: e926a45316a2
Create Date: 2026-09-20 23:27:16.966522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5636476777d'
down_revision: Union[str, Sequence[str], None] = 'e926a45316a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ledger_entries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('account', sa.Enum('CLIENT', 'ESCROW', 'FREELANCER', name='ledgeraccount'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account'), 'ledger_entries', ['account'], unique=False)
    op.create_index(op.f('ix_ledger_entries_contract_id'), 'ledger_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_contract_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
